MONGODB_HOST: mongodb-{{ env }}.daws-90.online
REDIS_HOST: redis-{{ env }}.daws-90.online
MYSQL_HOST: mysql-{{ env }}.daws-90.online
RABBITMQ_HOST: rabbitmq-{{ env }}.daws-90.online
CATALOGUE_HOST: catalogue-{{ env }}.daws-90.online
USER_HOST: user-{{ env }}.daws-90.online
CART_HOST: cart-{{ env }}.daws-90.online
SHIPPING_HOST: shipping-{{ env }}.daws-90.online
PAYMENT_HOST: payment-{{ env }}.daws-90.online